export interface Country {
  code: string;
  name: string;
  cities: string[];
}

export const countries: Country[] = [
  {
    code: "BD",
    name: "Bangladesh",
    cities: [
      "Dhaka",
      "Chittagong",
      "Sylhet",
      "Khulna",
      "Rajshahi",
      "Rangpur",
      "Barisal",
      "Mymensingh",
      "Cumilla",
      "Narayanganj",
      "Gazipur",
      "Tongi",
      "Jessore",
      "Bogra",
      "Dinajpur",
    ],
  },
  {
    code: "US",
    name: "United States",
    cities: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Philadelphia",
      "San Antonio",
      "San Diego",
      "Dallas",
      "San Jose",
      "Austin",
      "Jacksonville",
      "Fort Worth",
      "Columbus",
      "Charlotte",
      "San Francisco",
      "Indianapolis",
      "Seattle",
      "Denver",
      "Washington DC",
      "Boston",
      "El Paso",
      "Nashville",
      "Detroit",
      "Oklahoma City",
      "Portland",
      "Las Vegas",
      "Memphis",
      "Louisville",
      "Baltimore",
    ],
  },
  {
    code: "IN",
    name: "India",
    cities: [
      "Mumbai",
      "Delhi",
      "Bangalore",
      "Hyderabad",
      "Ahmedabad",
      "Chennai",
      "Kolkata",
      "Surat",
      "Pune",
      "Jaipur",
      "Lucknow",
      "Kanpur",
      "Nagpur",
      "Indore",
      "Thane",
      "Bhopal",
      "Visakhapatnam",
      "Pimpri-Chinchwad",
      "Patna",
      "Vadodara",
      "Ghaziabad",
      "Ludhiana",
      "Agra",
      "Nashik",
      "Faridabad",
    ],
  },
  {
    code: "CA",
    name: "Canada",
    cities: [
      "Toronto",
      "Montreal",
      "Vancouver",
      "Calgary",
      "Edmonton",
      "Ottawa",
      "Winnipeg",
      "Quebec City",
      "Hamilton",
      "Kitchener",
      "London",
      "Victoria",
      "Halifax",
      "Oshawa",
      "Windsor",
      "Saskatoon",
      "St. Catharines",
      "Regina",
      "Sherbrooke",
      "Barrie",
    ],
  },
  {
    code: "GB",
    name: "United Kingdom",
    cities: [
      "London",
      "Birmingham",
      "Manchester",
      "Leeds",
      "Liverpool",
      "Sheffield",
      "Bristol",
      "Glasgow",
      "Leicester",
      "Edinburgh",
      "Coventry",
      "Bradford",
      "Cardiff",
      "Belfast",
      "Nottingham",
      "Hull",
      "Newcastle",
      "Stoke-on-Trent",
      "Southampton",
      "Derby",
    ],
  },
  {
    code: "AU",
    name: "Australia",
    cities: [
      "Sydney",
      "Melbourne",
      "Brisbane",
      "Perth",
      "Adelaide",
      "Gold Coast",
      "Newcastle",
      "Canberra",
      "Sunshine Coast",
      "Wollongong",
      "Hobart",
      "Geelong",
      "Townsville",
      "Cairns",
      "Darwin",
      "Toowoomba",
      "Ballarat",
      "Bendigo",
      "Albury",
      "Launceston",
    ],
  },
  {
    code: "DE",
    name: "Germany",
    cities: [
      "Berlin",
      "Hamburg",
      "Munich",
      "Cologne",
      "Frankfurt",
      "Stuttgart",
      "Düsseldorf",
      "Dortmund",
      "Essen",
      "Leipzig",
      "Bremen",
      "Dresden",
      "Hanover",
      "Nuremberg",
      "Duisburg",
      "Bochum",
      "Wuppertal",
      "Bielefeld",
      "Bonn",
      "Münster",
    ],
  },
  {
    code: "FR",
    name: "France",
    cities: [
      "Paris",
      "Marseille",
      "Lyon",
      "Toulouse",
      "Nice",
      "Nantes",
      "Strasbourg",
      "Montpellier",
      "Bordeaux",
      "Lille",
      "Rennes",
      "Reims",
      "Le Havre",
      "Saint-Étienne",
      "Toulon",
      "Angers",
      "Grenoble",
      "Dijon",
      "Nîmes",
      "Aix-en-Provence",
    ],
  },
];

export function getCountryByCode(code: string): Country | undefined {
  return countries.find((country) => country.code === code);
}

export function getCitiesByCountryCode(countryCode: string): string[] {
  const country = getCountryByCode(countryCode);
  return country ? country.cities : [];
}
